# Generated by Django 2.2.4 on 2019-08-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='imgs/animals/')),
                ('age', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('F', 'femea'), ('M', 'macho')], default='F', max_length=1)),
                ('specie', models.CharField(choices=[('cachorro', 'cachorro'), ('gato', 'gato')], default='cachorro', max_length=225)),
                ('size', models.CharField(choices=[('pequeno', 'pequeno'), ('medio', 'medio'), ('grande', 'grande'), ('extra grande', 'extra grande')], default='pequeno', max_length=225)),
                ('category', models.CharField(choices=[('achado', 'achado'), ('perdido', 'perdido'), ('adoção', 'adoção')], default='achado', max_length=225)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pets.User')),
            ],
        ),
    ]
