# Generated by Django 2.2.4 on 2019-08-24 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='imgs/animals/')),
                ('age', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('F', 'femea'), ('M', 'macho')], default='F', max_length=1)),
                ('specie', models.CharField(choices=[('cachorro', 'cachorro'), ('gato', 'gato')], default='cachorro', max_length=225)),
                ('size', models.CharField(choices=[('pequeno', 'pequeno'), ('medio', 'medio'), ('grande', 'grande'), ('extra grande', 'extra grande')], default='pequeno', max_length=225)),
                ('category', models.CharField(choices=[('achado', 'achado'), ('perdido', 'perdido'), ('adoção', 'adoção')], default='achado', max_length=225)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pets.Profile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
