# Generated by Django 2.2.4 on 2019-08-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pets', '0002_auto_20190817_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
