# Generated by Django 2.2.4 on 2019-08-22 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_pets', '0003_auto_20190817_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='animals',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='animals',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
