# Generated by Django 2.2.4 on 2019-08-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pets', '0003_auto_20190825_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
