# Generated by Django 2.2.4 on 2019-08-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pets', '0004_auto_20190825_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
